installation and importing pytorch and check for macos

In [1]:
import torch
print(torch.__version__)
print(torch.backends.mps.is_available())

2.11.0
True


Scalars, vectors, matrices, and tensors 

In [4]:
import torch

tensor0d = torch.tensor(1)

tensor1d = torch.tensor([1,2,3])

tensor2d = torch.tensor([[1,2],[3,4]])

tensor3d = torch.tensor([[[1,2],[3,4]], [[5,6],[7,8]]])

Tensor data types

In [5]:
print(tensor1d.dtype)

torch.int64


In [6]:
floatvec = torch.tensor([1.0 ,2.0 , 3.0])
print(floatvec.dtype)

torch.float32


Common PyTorch tensor operations 

In [8]:
tensor2d = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
print(tensor2d.shape)

torch.Size([2, 3])


In [10]:
tensor2d.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [14]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [15]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])

Seeing models as computation graphs